version: 2.1
orbs:
    snyk: snyk/snyk@0.0.8
jobs:
    build-test-monitor:
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            - run: npm install semantic-release @semantic-release/exec pkg --save-dev --legacy-peer-deps
            - run: npm install
            - run: npm test
            - snyk/scan:
                fail-on-issues: true
                monitor-on-build: true
                token-variable: SNYK_TOKEN
            - run: npx semantic-release
    build-test:
        parameters:
            node_version:
                type: string
                ocker:
        docker:
            - image: circleci/node:<< parameters.node_version >>
        steps:
            - checkout
            - run: npm install
            - run: npm run lint
            - run: npm test
            - snyk/scan:
                fail-on-issues: true
                monitor-on-build: false
                token-variable: SNYK_TOKEN
            - run: npx tsc
    build-test-from-fork:
        parameters:
            node_version:
                type: string
                ocker:
        docker:
            - image: circleci/node:<< parameters.node_version >>
        steps:
            - checkout
            - run: npm install
            - run: npm test
            - run: npx tsc
workflows:
    version: 2
    nightly:
        triggers:
          - schedule:
              cron: "0 0 * * *"
              filters:
                branches:
                  only:
                    - main
        jobs:
            - build-test-monitor:
                context: SNYK

    build-test-monitor:
        jobs:
            - build-test-monitor:
                context: SNYK
                filters:
                    branches:
                        only:
                            - main
    build-test:
        jobs:
            - build-test:
                context: SNYK
                matrix:
                    parameters:
                        node_version: [ '10', '12', '14' ]
                filters:
                    branches:
                        ignore:
                        - main
                        - /pull\/[0-9]+/
            - build-test-from-fork:
                matrix:
                    parameters:
                        node_version: [ '10', '12', '14' ]
                filters:
                    branches:
                        only:
                        - /pull\/[0-9]+/
